name: Apartment Check

on:
  schedule:
    - cron: '0 0 * * *'  # 00:00 UTC
    - cron: '0 12 * * *' # 12:00 UTC
  workflow_dispatch:     # Manual trigger

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger apartment check
        run: |
          curl -X POST https://boplatz-crawler-pnr9h8g6k-maximogarciamartinezs-projects.vercel.app/api/workflow/check
